blank_issues_enabled: false
contact_links:
  - name: First-time contributor?
    url: https://github.com/cosdata/cosdata?tab=readme-ov-file#getting-started // TODO - update with contributor guidelines link
    about: Follow these instructions to get started.
  - name: Cosdata Community Support
    url: https://discord.gg/qvm8FJJHPm
    about: Please ask and answer questions here.