name: "release-main-latest"

permissions:
  contents: write
  packages: write

on:
  workflow_run:
    workflows: ["CI"]
    types: ["completed"]
    branches: ["main"]

jobs:
  pre-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Release Latest Main"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies (Protobuf, MUSL tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler musl-tools

      - uses: dtolnay/rust-toolchain@1.85
        with:
          targets: x86_64-unknown-linux-musl

      - name: Add MUSL target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Set Environment Variables
        run: |
          echo "CARGO_BUILD_TARGET=x86_64-unknown-linux-musl" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build (Release with MUSL)
        run: cargo build --release --all-features

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest-${{ env.sha_short }}"
          prerelease: true
          name: "Development Build"
          replacesArtifacts: true
          artifacts: |
            config.toml
            LICENSE
            *.md
            target/x86_64-unknown-linux-musl/release/cosdata
